name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Directory
      run: mkdir -p ${{github.workspace}}/build
      
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++-13 make
    
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DCMAKE_CXX_COMPILER=g++-13
      
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make
      
    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: make test
